UniversityRegistrar/Models/Course.cs
using System;
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Course
  {
    public Course()
    {
      this.JoinEntities = new HashSet<Enrollment>();
    }
    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public string CourseNumber { get; set; }
    public int DepartmentId { get; set; }
    public virtual ICollection<Enrollment> JoinEntities { get; set; }
    public virtual Department Department { get; set; }
  }
}

UniversityRegistrar/Models/Department.cs
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Department
  {
    public int DepartmentId { get; set; }
    public string DepartmentName { get; set; }
    public virtual ICollection<Student> Students { get; set; }
    public virtual ICollection<Course> Courses { get; set; }
  }
}

UniversityRegistrar/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContextFactory : IDesignTimeDbContextFactory<UniversityRegistrarContext>
  {
    UniversityRegistrarContext IDesignTimeDbContextFactory<UniversityRegistrarContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();

      var builder = new DbContextOptionsBuilder<UniversityRegistrarContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new UniversityRegistrarContext(builder.Options);
    }
  }
}

UniversityRegistrar/Models/Enrollment.cs
namespace UniversityRegistrar.Models
{
  public class Enrollment
  {
    public int EnrollmentId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
    public bool Complete { get; set; }
    public virtual Student Student { get; set; }
    public virtual Course Course { get; set; }
  }
}

UniversityRegistrar/Models/Student.cs
using System;
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Student
  {
    public Student()
    {
      this.JoinEntities = new HashSet<Enrollment>();
    }
    public int StudentId { get; set; }
    public string StudentName { get; set; }
    public DateTime EnrollmentDate { get; set; }
    public int DepartmentId { get; set; }
    public virtual ICollection<Enrollment> JoinEntities { get; set; }
    public virtual Department Department { get; set; }
  }
}

UniversityRegistrar/Models/UniversityRegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContext : DbContext
  {
    public DbSet<Student> Students { get; set; }
    public DbSet<Course> Courses { get; set; }
    public DbSet<Enrollment> Enrollments { get; set; }
    public DbSet<Department> Departments { get; set; }

    public UniversityRegistrarContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

UniversityRegistrar/Controllers/CoursesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
  
}

UniversityRegistrar/Controllers/DepartmentsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
  public class DepartmentsController : Controller
  {
    private readonly UniversityRegistrarContext _db;
    
    public DepartmentsController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Department> model = _db.Departments.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Department department)
    {
      _db.Departments.Add(department);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }  
}

UniversityRegistrar/Controllers/EnrollmentsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
  public class EnrollmentsController : Controller
  {
    private readonly UniversityRegistrarContext _db;
    
    public EnrollmentsController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "StudentName");
      ViewBag.PageTitle = "Enrollments";
      return View(_db.Enrollments.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "StudentName");
      ViewBag.PageTitle = " Add Enrollment";
      return View();
    }

    [HttpPost]
    public ActionResult Create(int studentId, int courseId)
    {
      _db.Enrollments.Add(new Enrollment() { StudentId = studentId, CourseId = courseId });
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }  
}

UniversityRegistrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace UniversityRegistrar.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        ViewBag.PageTitle = "University Registrar";
        return View();
      }

    }
}

UniversityRegistrar/Controllers/StudentsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly UniversityRegistrarContext _db;
    
    public StudentsController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.PageTitle = "Students";
      var orderedList = _db.Students.OrderBy(student => student.StudentName);
      return View(orderedList.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "DepartmentName");
      ViewBag.PageTitle = "Add Student";
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student)
    {
      _db.Students.Add(student);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
  }
}

UniversityRegistrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h3>Add A Course:</h3>
@using (Html.BeginForm())
{
  @Html.Label("Course Name: ")
  @Html.TextBoxFor(model => model.CourseName)<br>
  @Html.Label("Select Department")
  @Html.DropDownList("DepartmentId")<br>
  <input type="submit" value="Add Course" />
}

<h4>@Html.ActionLink("Back To Courses", "Index")</h4>

UniversityRegistrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Course>;

<h2>Courses:</h2>
<hr />

@if (@Model.Count == 0)
{
  <h3>No Courses Added</h3>
  <hr />
}

@foreach(Course course in Model)
{
  <h5>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId })</h5>
  <hr />
}

<h4>@Html.ActionLink("Add New Course", "Create")</h4>
<h4>@Html.ActionLink("Home", "Index", "Home")</h4>

UniversityRegistrar/Views/Departments/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Department

<h4>Add Department</h4>
@using (Html.BeginForm())
{
  @Html.Label("Department Name:")<br>
  @Html.TextBoxFor(model => model.DepartmentName)
  <input type="submit" value="Add Department" />
}
<p>@Html.ActionLink("Show All Departments", "Index")</p>

UniversityRegistrar/Views/Departments/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Department>;

<h2>Departments:</h2>
<hr />

@if (@Model.Count == 0)
{
  <h3>No Departments Added</h3>
  <hr />
}

@foreach(Department department in Model)
{
  <h5>@Html.ActionLink($"{department.DepartmentName}", "Details", new { id = department.DepartmentId })</h5>
  <hr />
}

<h4>@Html.ActionLink("Add New Department", "Create")</h4>
<h4>@Html.ActionLink("Home", "Index", "Home")</h4>

UniversityRegistrar/Views/Enrollments/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Enrollment

<h4>Add Enrollment</h4>
@using (Html.BeginForm())
{
  @Html.Label("Select Student")
  @Html.DropDownList("StudentId")<br>
  @Html.Label("Select Courses")
  @Html.DropDownList("CourseId")

  @* <ul>
  @foreach (var course in ViewBag.Courses)
  {
    
    @Html.Display(course.CourseName)
  } *@
  <input type="submit" value="Add Enrollment" />
  
}
<p>@Html.ActionLink("Show All Departments", "Index")</p>

UniversityRegistrar/Views/Enrollments/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Enrollment>;

<h2>Enrollments:</h2>
<hr />

@if (@Model.Count == 0)
{
  <h3>No Enrollments Added</h3>
  <hr />
}

@foreach(Enrollment enrollment in Model)
{
  <h5>@Html.Label($"{enrollment.Student.StudentName} - {enrollment.Course.CourseName} - Complete: {enrollment.Complete}")</h5>
  <hr />
}

<h4>@Html.ActionLink("Add New Enrollment", "Create")</h4>
<h4>@Html.ActionLink("Home", "Index", "Home")</h4>

UniversityRegistrar/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>University Registrar</h1>
<hr />
<h3>@Html.ActionLink("See All Courses", "Index", "Courses")</h3>
<h3>@Html.ActionLink("See All Students", "Index", "Students")</h3>
<h3>@Html.ActionLink("See All Departments", "Index", "Departments")</h3>
<h3>@Html.ActionLink("See All Enrollments", "Index", "Enrollments")</h3>

UniversityRegistrar/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

UniversityRegistrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.PageTitle</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
      @await Html.PartialAsync("Footer")
    </div>
  </body>
</html>

UniversityRegistrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h3>Add A Student</h3>
@using (Html.BeginForm())
{
  @Html.Label("Student Name: ")
  @Html.TextBoxFor(model => model.StudentName)<br>
  @Html.Label("Enrollment Date: ")
  @Html.Editor("EnrollmentDate")<br>
  @Html.Label("Select Department")
  @Html.DropDownList("DepartmentId")<br>
  <input type="submit" value="Add Student" />
}

<h4>@Html.ActionLink("Back To Students", "Index")</h4>

UniversityRegistrar/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Student>;

<h2>Students:</h2>
<hr />

@if (@Model.Count == 0)
{
  <h3>No Students Added</h3>
  <hr />
}

@foreach(Student student in Model)
{
  <h5>@Html.ActionLink($"{student.StudentName}", "Details", new { id = student.StudentId })</h5>
  <hr />
}

<h4>@Html.ActionLink("Add New Student", "Create")</h4>
<h4>@Html.ActionLink("Home", "Index", "Home")</h4>